src/digitalmarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', CheckoutTestView.as_view(), name='test'),
    path('checkout/', CheckoutAjaxView.as_view(), name='checkout'),
    path('admin/', admin.site.urls),
    path('seller/', include('sellers.urls', namespace='sellers')),
    path('products/', include('products.urls', namespace='products')),
    path('tags/', include('tags.urls', namespace='tags')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tags/urls.py
from django.urls import path, include
from .views import TagDetailView, TagListView

app_name = 'tags'
urlpatterns = [
    path('', TagListView.as_view(), name='list'),
    path('<slug:slug>/', TagDetailView.as_view(), name='detail'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css\base.css' %}">
    <meta charset="UTF-8">
    <title>Marketplace</title>
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
<nav class="main-nav">
    <ul class="pull-left first-nav">
        <li lca><a href="{% url 'dashboard' %}">Digital Marketplace</a> </li>
    </ul>
    <ul class="pull-right">
        <li><a href="{% url 'products:list' %}">Products</a> </li>
        <li><a href="{% url 'tags:list' %}">Tags</a> </li>
        <li><a href="#">Library</a> </li>
    </ul>
</nav>
<div class="main-content">
{% block content %}
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<script src="{% static 'js\django.csrf.js' %}"></script>

<script>
    $(document).ready(function () {
        {% block jquery %}
        {% endblock %}
    })
</script>
</body>
</html>

src/templates/create_view.html
{% extends "base.html" %}
{%block content %}
{% include "form_include.html" with form=form submit_btn="Create product"%}

{% endblock %}

src/templates/detail_view.html
{% extends "base.html" %}
{%block content %}
<h1>{{obj.title}}</h1>
<p>{{obj.description}}</p>
<span />
<h5>{{obj.price}}</h5>
<a href="{% url 'update_view' obj.slug %}">Edit</a>
<a href="{% url 'list_view' %}">List</a>
{% endblock %}

src/templates/form_include.html
<form method="post" action="">
    {% csrf_token %}
{{form.as_p}}
    <input type="submit" value="{{submit_btn}}" />
</form>

src/templates/list_view.html
{% extends "base.html" %}
{%block content %}
<h1>List of Products</h1>
<ul>
    {% for item in obj %}
    <li>
        <h2><a href="{% url 'detail_view' item.slug %}">{{item.title}}</a></h2>
    </li>
    {% endfor %}
</ul>
{% endblock %}

src/templates/update_view.html
{% extends "base.html" %}
{%block content %}
{% include "form_include.html" with form=form submit_btn="Update product"%}
{% endblock %}