src/digitalmarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', CheckoutTestView.as_view(), name='test'),
    path('checkout/', CheckoutAjaxView.as_view(), name='checkout'),
    path('admin/', admin.site.urls),
    path('seller/', include('sellers.urls', namespace='sellers')),
    path('products/', include('products.urls', namespace='products')),
    path('tags/', include('tags.urls', namespace='tags')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path, include
from .views import (detail_view, list_view, create_view, update_view,
                    ProductListView, ProductDetailView, ProductCreateView,
                    ProductUpdateView, ProductDownloadView, ProductRatingAjaxView)
app_name = 'products'
urlpatterns = [
    #path('<int:id>/', detail_view, name='detail_view'),
    path('', ProductListView.as_view(), name='list'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='detail'),
    path('product/<slug:slug>/edit/', ProductUpdateView.as_view(), name='update'),
    path('product/<slug:slug>/download/', ProductDownloadView.as_view(), name='download'),
    path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating')

    #
    # path('create/',create_view, name='create_view'),
    # path('<slug:slug>/edit/', update_view, name='update_view'),
    # path('<slug:slug>/', detail_view, name='detail_view'),
    # path('',list_view, name='list_view'),

]

src/tags/urls.py
from django.urls import path, include
from .views import TagDetailView, TagListView

app_name = 'tags'
urlpatterns = [
    path('', TagListView.as_view(), name='list'),
    path('<slug:slug>/', TagDetailView.as_view(), name='detail'),
]

src/billing/models.py
from django.db import models
from django.conf import settings
from products.models import Product

# Create your models here.

class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=100, decimal_places=2, default=9.99, null=True, )
    timestamp = models.DateTimeField(auto_now_add=True)
    success = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id}"

src/products/models.py
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.text import slugify

from sellers.models import SellerAccount


def download_media_location(instance, filename):
    return f"{instance.slug}/{filename}"


class Product(models.Model):
    seller = models.ForeignKey(SellerAccount, on_delete=models.CASCADE)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="managers_products", blank=True)
    media = models.ImageField(blank=True,
                              null=True,
                              upload_to=download_media_location,
                              storage=FileSystemStorage(location=settings.PROTECTED_ROOT))
    title = models.CharField(max_length=30)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=100, decimal_places=2, default=9.99, null=True, )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        view_name = "products:detail"
        return reverse(view_name, kwargs={"slug": self.slug})

    def get_edit_url(self):
        view_name = "sellers:product_update"
        return reverse(view_name, kwargs={"slug": self.slug})

    def get_download(self):
        view_name = "products:download"
        url = reverse(view_name, kwargs={"slug": self.slug})
        return url


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = f'{slug}-{qs.first().id}'
        return create_slug(instance, new_slug=new_slug)
    return slug


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)


def thumbnail_location(instance, filename):
    return f"{instance.product.slug}/{filename}"


THUMB_CHOICES = (
    ("hd", "HD"),
    ("sd", "SD"),
    ("micro", "Micro"),
)


class Thumbnail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    type = models.CharField(max_length=20, choices=THUMB_CHOICES, default='hd')
    height = models.CharField(max_length=20, null=True, blank=True)
    width = models.CharField(max_length=20, null=True, blank=True)
    media = models.ImageField(
        width_field="width",
        height_field="height",
        blank=True,
        null=True,
        upload_to=thumbnail_location)

    def __str__(self):
        return str(self.media.path)


import os
import shutil
from PIL import Image
import random

from django.core.files import File

def create_thumb(media_path, instance, owner_slug, max_length, max_width):
    filename = os.path.basename(media_path)
    thumb = Image.open(media_path)
    size = (max_length, max_width)
    thumb.thumbnail(size, Image.ANTIALIAS)
    temp_loc = os.path.join(settings.MEDIA_ROOT, owner_slug, 'tmp')
    if not os.path.exists(temp_loc):
        os.makedirs(temp_loc)
    temp_file_path = os.path.join(temp_loc, filename)
    if os.path.exists(temp_file_path):
        temp_path = os.path.join(temp_loc, f"{random.random()}")
        os.makedirs(temp_path)
        temp_file_path = os.path.join(temp_path, filename)

    temp_image = open(temp_file_path, "wb")
    thumb.save(temp_image)
    thumb_data = open(temp_file_path, "rb")

    thumb_file = File(thumb_data)
    instance.media.save(filename, thumb_file)
    shutil.rmtree(temp_loc, ignore_errors=True)
    return True

def product_post_save_receiver(sender, instance, created, *args, **kwargs):
    if instance.media:
        hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
        sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
        micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')

        hd_max = (400, 400)
        sd_max = (200, 200)
        micro_max = (50, 50)
        media_path = instance.media.path
        owner_slug = instance.slug
        if hd_created:
            create_thumb(media_path, hd, owner_slug, *hd_max)
            #
            # filename = os.path.basename(instance.media.path)
            # thumb = Image.open(instance.media.path)
            # thumb.thumbnail(hd_max, Image.ANTIALIAS)
            # temp_loc = os.path.join(settings.MEDIA_ROOT, instance.slug, 'tmp')
            # if not os.path.exists(temp_loc):
            #     os.makedirs(temp_loc)
            # temp_file_path = os.path.join(temp_loc, filename)
            # if os.path.exists(temp_file_path):
            #     temp_path = os.path.join(temp_loc, f"{random.random()}")
            #     os.makedirs(temp_path)
            #     temp_file_path = os.path.join(temp_path, filename)
            #
            # temp_image = open(temp_file_path, "wb")
            # thumb.save(temp_image)
            # thumb_data = open(temp_file_path, "rb")
            #
            # thumb_file = File(thumb_data)
            # hd.media.save(filename, thumb_file)

        if sd_created:
            create_thumb(media_path, sd, owner_slug, *sd_max)

        if micro_created:
            create_thumb(media_path, micro, owner_slug, *micro_max)

    # shutil.rmtree(temp_loc, ignore_errors=True)


post_save.connect(product_post_save_receiver, sender=Product)


class MyProducts(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return f"{self.products.count()}"

    class Meta:
        verbose_name = "My Products"
        verbose_name_plural = "My Products"

class ProductRating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(null=True, blank=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.rating}"

src/products/views.py
import os
from mimetypes import guess_type
from wsgiref.util import FileWrapper

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Q, Avg, Count
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from digitalmarket.mixins import AjaxRequiredMixin
from .mixin import ProductManagerMixin
from sellers.mixin import SellerAccounMixin
from analytics.models import TagView
from .models import Product, ProductRating
from tags.models import Tag
from .forms import ProductAddForm, ProductModelForm
# Create your views here.

class ProductRatingAjaxView(AjaxRequiredMixin, View):
    def post(self, request):
        if not request.user.is_authenticated:
            return JsonResponse({}, status=401)
        user = request.user
        product_id = request.POST.get("product_id")
        rating_value = request.POST.get("rating_value")
        exist = Product.objects.filter(id=product_id).exists()
        if not exist:
            return JsonResponse({}, status=404)
        try:
            product_obj = Product.objects.get(id=product_id)
        except:
            product_obj = Product.objects.filter(id=product_id).first()

        rating_obj, rating_obj_created = ProductRating.objects.get_or_create(user=user, product=product_obj)

        try:
            rating_obj = ProductRating.objects.get(user=user, product=product_obj)
        except ProductRating.MultipleObjectsReturned:
            rating_obj = ProductRating.objects.filter(user=user, product=product_obj).first()
        except:
            rating_obj = ProductRating.objects.create(user=user, product=product_obj)

        rating_obj.rating = int(rating_value)
        myproducts = user.myproducts.products.all()
        if product_obj in myproducts:
            rating_obj.verified = True
        rating_obj.save()

        data = {
            "success": True
        }
        return JsonResponse(data)


class ProductUpdateView(ProductManagerMixin, UpdateView):
    model = Product
    template_name = 'update_view.html'
    form_class = ProductModelForm
    success_url = reverse_lazy('products:list')

    def get_initial(self):
        initial = super(ProductUpdateView, self).get_initial()
        tags = self.get_object().tag_set.all()
        initial['tags'] = ', '.join([x.title for x in tags])
        return initial

    # def get_object(self, queryset=None):
    #     user = self.request.user
    #     obj = super(ProductUpdateView, self).get_object()
    #     if obj.seller == user:
    #     #if obj.user == user or user in obj.managers.all():
    #         return obj
    #     else:
    #         raise Http404

    def form_valid(self, form):
        valid_data = super(ProductUpdateView, self).form_valid(form)
        print(form.cleaned_data)
        tags = form.cleaned_data.get('tags')
        obj = self.get_object()
        obj.tag_set.clear()
        if tags:
            tag_list = tags.split(',')
            for tag in tag_list:
                if tag != "":
                    new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
                    new_tag.products.add(self.get_object())
        return valid_data

class ProductCreateView(SellerAccounMixin, CreateView):
    model = Product
    template_name = 'create_view.html'
    form_class = ProductModelForm
    # success_url = reverse_lazy('products:list')

    def form_valid(self, form):
        # user = self.request.user
        # form.instance.user = user
        seller = self.get_account()
        form.instance.seller = seller
        valid_data = super(ProductCreateView, self).form_valid(form)
        tags = form.cleaned_data.get('tags')
        if tags:
            tag_list = tags.split(',')
            for tag in tag_list:
                if tag != "":
                    new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
                    new_tag.products.add(form.instance)
        return valid_data

class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        obj = self.get_object()
        tags = obj.tag_set.all()
        rating_avg = obj.productrating_set.aggregate(Avg("rating"), Count("rating"))
        context["rating_avg"] = rating_avg
        if self.request.user.is_authenticated:
            rating_obj = ProductRating.objects.filter(user=self.request.user, product=obj)
            if rating_obj.exists():
                context["my_rating"] = rating_obj.first().rating
            for tag in tags:
                TagView.objects.add_count(user=self.request.user, tag=tag)
        return context

class ProductDownloadView(DetailView):
    model = Product
    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj in request.user.myproducts.products.all():
            filepath = os.path.join(settings.PROTECTED_ROOT, obj.media.path)
            guessed_type = guess_type(filepath)[0]
            wrapper = FileWrapper(open(filepath, 'rb'))
            # mimetype = 'application/force-download'
            # if guessed_type:
            #     mimetype = guessed_type
            mimetype = guessed_type if guessed_type else 'application/force-download'
            responce = HttpResponse(wrapper, content_type=mimetype)
            if not request.GET.get('preview'):
                responce["Content-Disposition"] = f"attachment; filename={obj.media.name}"
            #responce["Content-Disposition"] = f"attachment; filename={obj.media.name}"
            responce["X-SendFile"] = str(obj.media.name)
            return responce
        else:
            raise Http404


class SellerProductListView(SellerAccounMixin, ListView):
    model = Product
    template_name = "sellers/product_list_view.html"
    def get_queryset(self):
        qs = super(SellerProductListView, self).get_queryset()
        qs = qs.filter(seller=self.get_account())
        query = self.request.GET.get('q')
        if query:
            qs = qs.filter(
                Q(title__icontains = query)|
                Q(description__icontains = query)
            )
        return qs



class ProductListView(ListView):
    model = Product
    def get_queryset(self):
        qs = super(ProductListView, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            qs = qs.filter(
                Q(title__icontains = query)|
                Q(description__icontains = query)
            )
        return qs


def create_view(request):
    if request.method == "POST":
        form = ProductModelForm(request.POST)
        if form.is_valid():
            try:
                form.save()
            except IntegrityError:
                instance = form.save(commit=False)
                instance.slug += '-n'
                instance.save()
        return redirect('list_view')
    else:
        form = ProductModelForm()
    # if form.is_valid():
    #     form_data = form.cleaned_data
    #     new_obj = Product.objects.create(title=form_data.get('title'),
    #                                      description=form_data.get('description'),
    #                                      price=form_data.get('price'))
    template = 'create_view.html'
    context = {'form':form}
    return render(request, template, context)

def update_view(request, slug):
    obj = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        form = ProductModelForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
        return redirect('detail_view', slug=slug)
    else:
        form = ProductModelForm(instance=obj)
    template = 'update_view.html'
    context = {'form': form}
    return render(request, template, context)

def detail_view(request, slug):
    obj = get_object_or_404(Product, slug=slug)
    #obj = Product.objects.get(pk=id)
    template = 'detail_view.html'
    context = {'obj':obj}
    return render(request, template, context)

def list_view(request):
    obj = Product.objects.all()
    template = 'list_view.html'
    context = {'obj':obj}
    return render(request, template, context)

src/templates/products/product_detail.html
{% extends "base.html" %}

<script>
    $(document).ready(function () {
        {% block jquery %}
        $(".rating input[value='{{my_rating}}']").attr("checked", "checked")
        $(".rating input[type='radio']").click(function (event) {
            var inputValue = $(this).val()
            console.log(inputValue);
            var request = $.ajax({
                        method: "POST",
                        url: "{% url 'products:ajax_rating' %}",
                        data: {
                            product_id: "{{ object.id }}",
                            rating_value: inputValue,
                        },
                    })
                request.done(function (data) {
                    console.log(data)
                })
                request.fail(function (jqXHR, textStatus) {
                    if (jqXHR.status == 404) {
                        alert("Page not found!")
                    } else {
                        alert("There was an error with your request. Please, try again.")
                    }
                })
        })

        $("#purchase-btn").click(function (event) {
            event.preventDefault()
            var purchaseBtn = $(this)
            $("#dialog-purchase").fadeIn("300")
            $("#dialog-purchase").dialog({
                resizable: false,
                height: 350,
                 width: 350,
                modal: true,
                buttons: {
                    1:{
                            id: "close",
                            text: "Confirm",
                            click: function () {
                                    var request = $.ajax({
                                                    method: "POST",
                                                    url: "{% url 'checkout' %}",
                                                    data: {
                                                        product_id: "{{ object.id }}",
                                                    },
                                                })
                                    request.done(function (data) {
                                        purchaseBtn.before("<p><a href='" + data.download + "'>Download</a></p><p><a href='" + data.preview + "'>Preview</a></p>")
                                        purchaseBtn.fadeOut(100)
                                        // console.log("working...")
                                        // if (data.works) {
                                        //     $("#content").html(data.time)
                                        // }
                                    })
                                    request.fail(function (jqXHR, textStatus) {
                                        if (jqXHR.status == 404) {
                                            alert("Page not found!")
                                        } else {
                                            alert("There was an error with your request. Please, try again.")
                                        }
                                    })
                                $( this ).dialog( "close" );
                            },
                            class: "buy-btn"
                        },
                    2:{
                            id: "close",
                            text: "Cancel",
                            click: function () {
                                $( this ).dialog( "close" );
                            },
                            class: "cancel-btn"
                        },
                    }
            })
        })
        {% endblock %}
    })
</script>
<style>
{% block style %}
.rating {
    float:left;
    width: 200px;
}

/* :not(:checked) is a filter, so that browsers that don’t support :checked don’t
   follow these rules. Every browser that supports :checked also supports :not(), so
   it doesn’t make the test unnecessarily selective */
.rating:not(:checked) > input {
    position:absolute;
    top:-9999px;
    clip:rect(0,0,0,0);
}

.rating:not(:checked) > label {
    float:right;
    width:1em;
    padding:0 .1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:200%;
    line-height:1.2;
    color:#ddd;
    text-shadow:1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0,0,0,.5);
}

.rating:not(:checked) > label:before {
    content: '★ ';
}

.rating > input:checked ~ label {
    color: #f70;
    text-shadow:1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0,0,0,.5);
}

.rating:not(:checked) > label:hover,
.rating:not(:checked) > label:hover ~ label {
    color: gold;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}

.rating > input:checked + label:hover,
.rating > input:checked + label:hover ~ label,
.rating > input:checked ~ label:hover,
.rating > input:checked ~ label:hover ~ label,
.rating > label:hover ~ input:checked ~ label {
    color: #ea0;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}

.rating > label:active {
    position:relative;
    top:2px;
    left:2px;
}
{% endblock %}
</style>

{%block content %}
<div class="col-primary pull-left">
<h1>{{object.title}}</h1>
<p>{{object.description}}</p>
<span />

<h5>{{object.price}}</h5>

    <p>
    Purchase: {{object.transaction_set.count }}
    </p>

    <p>
    {% for img in object.thumbnail_set.all %}
    <img src="{{img.media.url}}" />
    {% endfor %}
  </p>

    <p>
    <a href="{% url 'products:list' %}">List</a>
    <a href="{% url 'products:update' object.slug %}">Edit</a>
    </p>
</div>
<div class="col-sidebar pull-right">
    {% if request.user.is_authenticated and object.media and object in request.user.myproducts.products.all%}
    <p><a href="{{ object.get_download }}">Download</a></p>
    <p><a href="{{ object.get_download }}?preview=True">Preview</a></p>
    {% else %}
        <p><a id="purchase-btn" href="sdfsdfsf">Purchase</a> </p>
        <div id="dialog-purchase" title="Confirm Purchase" style="display: none">
            <p>Your card will be charged after you agree below.</p>
        </div>
    {% endif %}

          <p>
              <strong>My Rating</strong>
<div class="rating">
    <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
    <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
    <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
    <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
    <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
</div>
    <p>
        {{rating_avg.rating__avg}} average rating by {{rating_avg.rating__count}} users
    </p>
</p>

</div>
<div class="clearfix"></div>
{% endblock %}

src/templates/products/product_list.html
{% extends "base.html" %}

{% block content %}
<h2>Products</h2>
<p>
    <form method="get" action="">
    <input type="text" name="q" placeholder="search">
    <input type="submit" value="Search">
</form>
</p>
    <ul>
        {% include "products/product_list_snippet.html" with product_list=object_list %}
    </ul>
{% endblock %}

src/templates/products/product_list_snippet.html
{% load get_thumbnail %}
{% for product in product_list %}
    <li><a href={{ product.get_absolute_url }}> {{ product.title }}</a> <br>
<!--        {% if product|get_thumbnail:'micro' %}-->
        <a href={{ product.get_absolute_url }}>
            <img src="{{ product|get_thumbnail:'micro' }}">
        </a><br>
<!--        {% endif %}-->
        Price: {{ product.price }}</li>
{% empty %}
<h3>No Products yet</h3>
{% endfor %}