src/digitalmarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', CheckoutTestView.as_view(), name='test'),
    path('checkout/', CheckoutAjaxView.as_view(), name='checkout'),
    path('admin/', admin.site.urls),
    path('seller/', include('sellers.urls', namespace='sellers')),
    path('products/', include('products.urls', namespace='products')),
    path('tags/', include('tags.urls', namespace='tags')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sellers/urls.py
from django.urls import path, include
from .views import SellerDashboard, SellerTransactionListView, SellerProductDetailRedirectView
from products.views import ProductCreateView, SellerProductListView, ProductUpdateView
app_name = 'sellers'
urlpatterns = [
    path('', SellerDashboard.as_view(), name='dashboard'),
    path('transactions/', SellerTransactionListView.as_view(), name='transactions'),
    path('products/', SellerProductListView.as_view(), name='product_list'),
    path('product/<slug:slug>/', SellerProductDetailRedirectView.as_view()),
    path('product/<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/add/', ProductCreateView.as_view(), name='product_create'),
]

src/tags/urls.py
from django.urls import path, include
from .views import TagDetailView, TagListView

app_name = 'tags'
urlpatterns = [
    path('', TagListView.as_view(), name='list'),
    path('<slug:slug>/', TagDetailView.as_view(), name='detail'),
]

src/billing/models.py
from django.db import models
from django.conf import settings
from products.models import Product

# Create your models here.

class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=100, decimal_places=2, default=9.99, null=True, )
    timestamp = models.DateTimeField(auto_now_add=True)
    success = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id}"

src/sellers/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class SellerAccount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="manager_sellers", blank=True)
    active = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return str(self.user.username)

src/sellers/forms.py
from django import forms

class NewSellerForm(forms.Form):
    agreed = forms.BooleanField(label='Agreed to terms', widget=forms.CheckboxInput)

src/dashboard/views.py
import random

from django.shortcuts import render
from products.models import Product
# Create your views here.
# from django.views.generic.base import View
from django.views import View


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        tag_view = None
        top_tags = None
        products = None
        try:
            tag_view = request.user.tagview_set.all().order_by("-count")[:5]
        except:
            pass
        owned = None
        try:
            owned = self.request.user.myproducts.products.all()
        except:
            pass
        if tag_view:
            top_tags = [x.tag for x in tag_view]
            products = Product.objects.filter(tag__in=top_tags)
            if owned:
                products = products.exclude(pk__in=owned)
            products = products.distinct()
            products = sorted(products, key=lambda x: random.random())
        context = {
            'products': products,
            'top_tags': top_tags
        }
        return render(request, 'dashboard/view.html', context)

src/sellers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
# Create your views here.
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import FormMixin

from .forms import NewSellerForm
from .models import SellerAccount
from products.models import Product
from billing.models import Transaction
from .mixin import SellerAccounMixin

from django.shortcuts import get_object_or_404
from django.views.generic.base import RedirectView

class SellerProductDetailRedirectView(RedirectView):
    permanent = True
    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, slug=kwargs['slug'])
        return obj.get_absolute_url()


class SellerTransactionListView(SellerAccounMixin, ListView):
    model = Transaction
    template_name = "sellers/transaction_list_view.html"

    def get_queryset(self):
        return self.get_transaction()
        # account = SellerAccount.objects.filter(user=self.request.user)
        # if account.exists():
        #     account = account.first()
        #     products = Product.objects.filter(seller=account)
        #     return Transaction.objects.filter(product__in=products)
        # return []

class SellerDashboard(SellerAccounMixin, FormMixin, View):
    form_class = NewSellerForm
    success_url = "/seller/"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        apply_form = self.get_form()
        account = self.get_account()
        active = None
        context = {}
        if account:
            active = account.active
        if not account and not active:
            context["title"] = "Apply this form"
            context["apply_form"] = apply_form
        elif account and not active:
            context["title"] = "Account Pending"
        elif account and active:
            context["title"] = "Seller Dashboard"
            transactions_today = self.get_transactions_today()
            context["transactions_today"] = transactions_today
            context["today_sales"] = self.get_today_sales()
            context["total_sales"] = self.get_total_sales()
            context["products"] = self.get_products()
            context["transactions"] = self.get_transaction().exclude(pk__in=transactions_today)[:5]

        return render(request, "sellers/dashboard.html", context)

    def form_valid(self, form):
        valid_data = super(SellerDashboard, self).form_valid(form)
        obj = SellerAccount.objects.create(user=self.request.user)
        return valid_data

src/templates/sellers/dashboard.html
{% extends "base.html" %}

{% block content %}
<!--<h1>Seller Dashboard</h1>-->
<h1>{{ title }}</h1>

{% if apply_form %}
<form method="post" action=""> {% csrf_token %}
    Rules of use
<ol>
    <li>
        Be kind
    </li>
    <li>
        Don't steal
    </li>
</ol>
    {{ apply_form }}
    <button type="submit">Submit</button>
</form>
{% endif %}

{% if products %}
<div class="pull-right col-sidebar">
    <h4>My Products<br><small>
        <a href="{% url 'sellers:product_create' %}">Add</a> | <a href="{% url 'sellers:product_list' %}">All</a>
    </small></h4>
{% include "products/product_list_snippet.html" with product_list=products %}
</div>
{% endif %}

{% if transactions %}
<div class="pull-left col-primary">
    <h3>Today's sales ({{ today_sales }}$)</h3>
    {% include "sellers/transaction_list.html" with transaction_list=transactions_today %}
    <br>
    <h3>Recent transaction history (Total:{{total_sales}}$)</h3>
{% include "sellers/transaction_list.html" with transaction_list=transactions %}
    <p>
        <a href="{% url 'sellers:transactions' %}">View all transactions</a>
    </p>
</div>
{% endif %}

{% endblock %}

src/templates/sellers/product_list_view.html
{% extends "base.html" %}
{% load get_thumbnail %}


{% block content %}
<h2>My Seller Products</h2>
<p>
    <form method="get" action="">
    <input type="text" name="q" placeholder="search">
    <input type="submit" value="Search">
</form>
</p>
    <table>

{% for product in object_list %}
    <tr>
        <td>
            {{product.id}}
        </td>
        <td>
            <a href={{ product.get_absolute_url }}> {{ product.title }}</a>
        </td>
        <td>
            <a href={{ product.get_absolute_url }}>
            <img src="{{ product|get_thumbnail:'micro' }}">
        </a>
        </td>
        <td>
            Price: {{ product.price }}
        </td>
        <td>
            <a href="{{product.get_edit_url}}">Edit</a> | <a href="#">Delete</a>
        </td>
    </tr>
{% empty %}
<h3>No Products yet</h3>
{% endfor %}

    </table>
{% endblock %}

src/templates/sellers/transaction_list.html
<table>
    <thead>
        <th>Product</th>
        <th>User</th>
        <th>Price</th>
        <th></th>
    </thead>
    <tbody>
        {% for trans in transaction_list %}
        <tr>
            <td>{{trans.product}}</td>
            <td>{{trans.user}}</td>
            <td>{{trans.price}}</td>
            <td>{{trans.timestamp|timesince}} ago</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

src/templates/sellers/transaction_list_view.html
{% extends "base.html" %}

{% block content %}
<h2>Transactions</h2>

    <ul>
    {% include "sellers/transaction_list.html" with transaction_list=object_list %}
    </ul>

{% endblock %}